apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cluster-observability-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cluster-observability-operator-group
  namespace: openshift-cluster-observability-operator
spec:
  targetNamespaces: [] 
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-observability-operator
  namespace: openshift-cluster-observability-operator
spec:
  channel: stable
  name: cluster-observability-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic

---

apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: monitoring
spec:
  monitoring:
    acm:
      alertmanager:
        url: 'http://observability-alertmanager.open-cluster-management-observability.svc.cluster.local:9093'
      enabled: true
      thanosQuerier:
        url: 'http://observability-thanos-query.open-cluster-management-observability.svc.cluster.local:9090'
    perses:
      enabled: true
  type: Monitoring
